#
# This file contains configuration flags to customize your site
#

# or set your shell JEKYLL_ENV to 'production'
env: production
production: true

# site-wide meta data
name: BBC GEL Test Rig
description: "An automated test fig for GEL, The Global Experience Language for the BBC."
keywords: "BBC, Design, UX, tests"

collections:
  fixtures:
    output: true
    permalink: fixtures/:path/
  guides:
    output: true
    permalink: guides/:path/


# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#        layout: post

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/gel-test"

# Use these gems
markdown: kramdown
highlighter: pygments

# configure
kramdown:
  auto_id_prefix: "gel-"
  toc_levels: "2"

# The release of Jekyll Now that you're using
version: v2.4.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # Use :expanded or use :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - src